plugins {
    id 'java-library'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(findProperty('javaToolchainVersion') ? Integer.parseInt(findProperty('javaToolchainVersion')) : 21)
    }
    withSourcesJar()
    withJavadocJar()
}

tasks.withType(JavaCompile).configureEach {
    options.release = 21
    options.encoding = 'UTF-8'
    options.compilerArgs += ['-Xlint:all', '-Xlint:-processing', '-Werror']
}

ext {
    springBootVersion = project.findProperty('springBootVersion') ?: '3.3.5'
}

dependencies {
    api project(':')
    compileOnly "org.springframework.boot:spring-boot-autoconfigure:${springBootVersion}"
    compileOnly 'org.springframework.security:spring-security-core:6.3.3'
    compileOnly 'org.springframework:spring-web:6.1.13'
    compileOnly 'org.slf4j:slf4j-api:2.0.16'

    annotationProcessor "org.springframework.boot:spring-boot-configuration-processor:${springBootVersion}"

    testImplementation platform('org.junit:junit-bom:5.11.4')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testImplementation "org.springframework.boot:spring-boot-starter-test:${springBootVersion}"
    testImplementation 'org.springframework.security:spring-security-core:6.3.3'
    testImplementation 'org.springframework:spring-web:6.1.13'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('test') {
    useJUnitPlatform()
}
